In [1]:
import pandas as pd
import geopy.distance

In [2]:
# pd.read_csv('dist_Ind.csv')

In [3]:
def clip_lat_lng(df, coords):
    """
    coords: ((lng_o, lng_e) ,(lat_s, lat_n))
    """
    ((O, E), (S, N)) = coords
    
    df_clip = df.loc[(df['lng'] > O) & (df['lng'] <= E) & (df['lat'] < N) & (df['lat'] >= S)]
    return df_clip

def f(x, col1 = 'coords_x', col2 = 'coords_y'):    
    return geopy.distance.vincenty(x[col1], x[col2]).km

In [4]:
import matplotlib.pyplot as plt
%matplotlib inline

In [5]:
# Load sedes, clip to amba, bring academic offer of such sedes.
sedes = pd.read_csv('sedes_loc_clean_z.csv').rename(columns = {'zona_id': 'zona_id_y'})
escuelas = pd.read_csv('escuelas_z.csv').rename(columns = {'zona_id': 'zona_id_x'})
oferta_apde = pd.read_csv('./oferta_apde.csv', sep = ';')

#Correct missing:
oferta_apde.loc[oferta_apde.Universidad == 'Universidad Nacional Guillermo Brown', 'existe_1988'] = False
oferta_apde.loc[oferta_apde.Universidad == 'Universidad Nacional Guillermo Brown', 'existe_2003'] = False

zonas_u = pd.read_csv('zonas_u.csv').rename(columns = {'zona_id': 'zona_id_y'})
zonas_s = pd.read_csv('zonas_s.csv').rename(columns = {'zona_id': 'zona_id_x'})

#clip AMBA
coords_AMBA = ((-59.2, -57.8), (-35.1, -34.05))
sedes_AMBA = clip_lat_lng(sedes, coords_AMBA)
#Only public
sedes_AMBA = sedes_AMBA.merge(oferta_apde[['Universidad', 'Ámbito']].drop_duplicates())
# sedes_AMBA_pub = sedes_AMBA.loc[sedes_AMBA['Ámbito'] == 'Público']

oferta_estrat_pub = oferta_apde.loc[(oferta_apde['Ámbito'] == 'Público') & oferta_apde['Estrategica']].merge(sedes[['Universidad', 'Facultad', 'zona_id_y']], how = 'left')
oferta_estrat_pub_AMBA = clip_lat_lng(oferta_estrat_pub.merge(zonas_u), coords_AMBA)
# # Load escuelas, clip to AMBA

# # index is set now:
# # escuelas = escuelas.groupby(['cue', 'nombre_estab', 'lat', 'lng', 'municipio', 'Provincia', 'sector de gestión'])['Matricula est 5to'].sum().reset_index().reset_index()

escuelas_AMBA = clip_lat_lng(escuelas, coords_AMBA)
# 

# Merge amount of people
zonas_s = zonas_s.merge(escuelas_AMBA.groupby('zona_id_x')['Matricula est 5to'].sum().reset_index())

In [6]:
# Compute distance matrix (to universities)

origenes = escuelas_AMBA[['zona_id_x', 'lat', 'lng']].drop_duplicates()
origenes['coords'] = list(zip(origenes.lat, origenes.lng))
print len(origenes)

results = []

for year in [1988, 2003, 2018]:
    for temas in [['Ingeniería', 'Otras Ciencias Aplicadas', 'Industrias'], \
                 ['Paramédicas y Auxiliares de Medicina', 'Medicina'], ['Informática'], \
                 ['Estadística', 'Física', 'Matemática'], ['Biología', 'Bioquímica y Farmacia', 'Química']]:

        ### A que zona (la mas cercana) tienen que ir los chicos a cursar? 

        # Condicion temas de estudio
        oferta_temas = oferta_estrat_pub_AMBA.loc[oferta_estrat_pub_AMBA.Disciplina.isin(temas)]

        # Condicion epoca (1988, 2003, 2018)
        if year == 1988:
            oferta_temas = oferta_temas.loc[oferta_temas.existe_1988]
        elif year == 2003:
            oferta_temas = oferta_temas.loc[oferta_temas.existe_2003]

        destinos = oferta_temas[['zona_id_y', 'lat', 'lng']].drop_duplicates()
        destinos['coords'] = list(zip(destinos.lat, destinos.lng))

        origenes['key'] = 0
        destinos['key'] = 0
        distances = pd.merge(origenes, destinos,on='key')#.set_index(['index','zona_id']).drop('key', axis = 1)

        distances['distance_km'] = distances.apply(f, axis=1)
        distances['ranking'] = distances.reset_index().groupby("zona_id_x")["distance_km"].rank().values
        distances = distances[['zona_id_x', 'zona_id_y','coords_x', 'coords_y','distance_km', 'ranking']]
        dist_mat_T = distances.set_index(['ranking', 'zona_id_x'])[['distance_km']].sort_index().unstack()
        ratio_clsest = (dist_mat_T/dist_mat_T.loc[1]).stack().rename(columns = {'distance_km': 'ratio_to_closest'}).reset_index()
        distances = distances.merge(ratio_clsest)

        distances['Temas'] = ', '.join(temas)
        distances['Year'] = year

        results += [distances.loc[distances.ratio_to_closest < 1.2]]
    # dist_mat = distances.unstack(0)['distance_km'].T
    # rank_mat = distances.unstack(0)['ranking'].T

3423

KeyboardInterrupt:

In [7]:
ref_escuelas = escuelas[['zona_id_x', 'nombre_estab']]#.rename(columns = {'zona_id': 'zona_id_x'})
ref_sedes = oferta_temas[['zona_id_y', 'Universidad', 'Facultad']].drop_duplicates()#.rename(columns = {'zona_id': 'zona_id_y'})

In [8]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [9]:
pd.concat(results).groupby(['Temas', 'Year']).count().iloc[:, 1]

Temas                                             Year
Ingeniería, Otras Ciencias Aplicadas, Industrias  1988    4661
Name: zona_id_y, dtype: int64

In [10]:
len(pd.concat(results)[['zona_id_x', 'zona_id_y']].drop_duplicates())

3488

In [11]:
# Costo en USD de las directions
_*5./1000

17.44

In [12]:
# pd.concat(results).merge(estudiantesxzona)
# estudiantesxzona = 
estudiantesxzona = escuelas[['zona_id_x', 'Matricula est 5to']].groupby('zona_id_x').sum()
# estudiantesxzona_wt = (estudiantesxzona/estudiantesxzona.sum()).reset_index().rename(columns = {'Matricula est 5to': 'Fraction_of_students\nschool_zone'})

In [13]:
results_wstud = pd.concat(results).merge(estudiantesxzona.reset_index())
# part_weighted.groupby(['Temas', 'Year']).nunique()

In [14]:
n_alternatives = results_wstud.groupby(['zona_id_x','Temas', 'Year'])['zona_id_y'].count().reset_index().rename(columns = {'zona_id_y': 'n_alternatives_tema_yr'})
n_students = results_wstud.groupby(['zona_id_x','Temas', 'Year'])['Matricula est 5to'].mean().reset_index().rename(columns = {'Matricula est 5to': 'n_students'})

In [15]:
f_students = n_students.groupby('zona_id_x')[['n_students']].mean()
f_students = (f_students/f_students.sum()).rename(columns = {'n_students': 'f_students'}).reset_index()

In [16]:
weighted = results_wstud.merge(n_alternatives, on = ['zona_id_x','Temas', 'Year']).merge(f_students, on = 'zona_id_x')
weighted['f_students_alternative_tema_yr'] = weighted['f_students'] / weighted['n_alternatives_tema_yr']

In [17]:
weighted['wt_distance'] = weighted['distance_km']*weighted['f_students_alternative_tema_yr']
weighted.groupby(['Temas', 'Year'])[['wt_distance']].sum()
# weighted.groupby(['Temas', 'Year'])[['f_students_alternative_tema_yr']].sum()

                                                       wt_distance
Temas                                            Year
Ingeniería, Otras Ciencias Aplicadas, Industrias 1988     8.544294

In [18]:
pd.concat(results).groupby(['Temas', 'Year'])['distance_km'].describe().round(1)

,,count,mean,std,min,25%,50%,75%,max
Temas,Year,,,,,,,,
"Ingeniería, Otras Ciencias Aplicadas, Industrias",1988,4661.0,9.7,6.8,0.0,5.1,8.4,12.4,54.1

In [233]:
# Save

pd.concat(results).to_csv('./results_distances.csv', index = False)

In [146]:
pd.concat(results).merge(ref_escuelas).merge(ref_sedes).sort_values(by = ['zona_id_x', 'zona_id_y', 'Year'])

,zona_id_x,zona_id_y,coords_x,coords_y,distance_km,ranking,ratio_to_closest,Temas,Year,nombre_estab,Universidad,Facultad
0,S0191,U008,"(-34.5592978754, -58.480213253)","(-34.5751866667, -58.4367866667)",4.357484,1.0,1.000000,"Ingeniería, Otras Ciencias Aplicadas",1988,Esc. Técnica N° 21 Fragata Escuela Libertad,"Instituto Universitario del Ejército ""Mayor Fr...",Unidad Académica Escuela Superior Técnica
1,S0191,U008,"(-34.5592978754, -58.480213253)","(-34.5751866667, -58.4367866667)",4.357484,1.0,1.000000,"Ingeniería, Otras Ciencias Aplicadas",1988,Esc. Técnica N° 21 Fragata Escuela Libertad,Universidad de la Defensa Nacional,Facultad del Ejército
2,S0191,U008,"(-34.5592978754, -58.480213253)","(-34.5751866667, -58.4367866667)",4.357484,1.0,1.000000,"Ingeniería, Otras Ciencias Aplicadas",1988,Inst. Sta. María de los Angeles,"Instituto Universitario del Ejército ""Mayor Fr...",Unidad Académica Escuela Superior Técnica
3,S0191,U008,"(-34.5592978754, -58.480213253)","(-34.5751866667, -58.4367866667)",4.357484,1.0,1.000000,"Ingeniería, Otras Ciencias Aplicadas",1988,Inst. Sta. María de los Angeles,Universidad de la Defensa Nacional,Facultad del Ejército
4,S0191,U008,"(-34.5592978754, -58.480213253)","(-34.5751866667, -58.4367866667)",4.357484,1.0,1.000000,"Ingeniería, Otras Ciencias Aplicadas",1988,Inst. Sta. Clara de Asís,"Instituto Universitario del Ejército ""Mayor Fr...",Unidad Académica Escuela Superior Técnica
5,S0191,U008,"(-34.5592978754, -58.480213253)","(-34.5751866667, -58.4367866667)",4.357484,1.0,1.000000,"Ingeniería, Otras Ciencias Aplicadas",1988,Inst. Sta. Clara de Asís,Universidad de la Defensa Nacional,Facultad del Ejército
8,S0191,U465,"(-34.5592978754, -58.480213253)","(-34.5729631, -58.5140043)",3.451622,1.0,1.000000,"Ingeniería, Otras Ciencias Aplicadas",2003,Esc. Técnica N° 21 Fragata Escuela Libertad,Universidad Nacional de San Martín,Instituto de Investigaciones Biotecnológicas
9,S0191,U465,"(-34.5592978754, -58.480213253)","(-34.5729631, -58.5140043)",3.451622,1.0,1.000000,"Ingeniería, Otras Ciencias Aplicadas",2003,Esc. Técnica N° 21 Fragata Escuela Libertad,Universidad Nacional de San Martín,Instituto de Tecnología Nuclear Dan Beninson
10,S0191,U465,"(-34.5592978754, -58.480213253)","(-34.5729631, -58.5140043)",3.451622,1.0,1.000000,"Ingeniería, Otras Ciencias Aplicadas",2003,Esc. Técnica N° 21 Fragata Escuela Libertad,Universidad Nacional de San Martín,Instituto de Tecnología Prof. Jorge Sábato
11,S0191,U465,"(-34.5592978754, -58.480213253)","(-34.5729631, -58.5140043)",3.451622,1.0,1.000000,"Ingeniería, Otras Ciencias Aplicadas",2003,Inst. Sta. María de los Angeles,Universidad Nacional de San Martín,Instituto de Investigaciones Biotecnológicas
12,S0191,U465,"(-34.5592978754, -58.480213253)","(-34.5729631, -58.5140043)",3.451622,1.0,1.000000,"Ingeniería, Otras Ciencias Aplicadas",2003,Inst. Sta. María de los Angeles,Universidad Nacional de San Martín,Instituto de Tecnología Nuclear Dan Beninson
13,S0191,U465,"(-34.5592978754, -58.480213253)","(-34.5729631, -58.5140043)",3.451622,1.0,1.000000,"Ingeniería, Otras Ciencias Aplicadas",2003,Inst. Sta. María de los Angeles,Universidad Nacional de San Martín,Instituto de Tecnología Prof. Jorge Sábato
14,S0191,U465,"(-34.5592978754, -58.480213253)","(-34.5729631, -58.5140043)",3.451622,1.0,1.000000,"Ingeniería, Otras Ciencias Aplicadas",2003,Inst. Sta. Clara de Asís,Universidad Nacional de San Martín,Instituto de Investigaciones Biotecnológicas
15,S0191,U465,"(-34.5592978754, -58.480213253)","(-34.5729631, -58.5140043)",3.451622,1.0,1.000000,"Ingeniería, Otras Ciencias Aplicadas",2003,Inst. Sta. Clara de Asís,Universidad Nacional de San Martín,Instituto de Tecnología Nuclear Dan Beninson
16,S0191,U465,"(-34.5592978754, -58.480213253)","(-34.5729631, -58.5140043)",3.451622,1.0,1.000000,"Ingeniería, Otras Ciencias Aplicadas",2003,Inst. Sta. Clara de Asís,Universidad Nacional de San Martín,Instituto de Tecnología Prof. Jorge Sábato
17,S0191,U465,"(-34.5592978754, -58.480213253)","(-34.5729631, -58.5140043)",3.451622,1.0,1.000000,"Ingeniería, Otras Ciencias Aplicadas",2018,Esc. Técnica N° 21 Fragata Escuela Libertad,Universidad Nacional de San Martín,Instituto de Investigaciones Biotecnológicas
18,S0191,U465,"(-34.5592978754, -58.480213253)","(-34.5729631, -58.5140043)",3.451622,1.0,1.000000,"Ingeniería, Otras Ciencias Aplicadas",2018,Esc. Técnica N° 21 Fragata Escuela Libertad,Universidad Nacional de San Martín,Instituto de Tecnología Nuclear Dan Beninson
19,S0191,U465,"(-34.5592978754, -58.480213253)","(-34.5729631, -58.5140043)",3.451622,1.0,1.000000,"Ingeniería, Otras Ciencias Aplicadas",2018,Esc. Técnica N° 21 Fragata Escuela Libertad,Universidad Nacional de San Martín,Instituto de Tecnología Prof. Jorge Sábato
20,S0191,U465,"(-34.5592978754, -58.480213253)","(-34.5729631, -58.5140043)",3.451622,1.0,1.000000,"Ingeniería, Otras Ciencias Aplicadas",2018,Inst. Sta. María de los Angeles,Universidad Nacional de San Martín,Instituto de Investigaciones Biotecnológicas
21,S0191,U465,"(-34.5592978754, -58.480213253)","(-34.5729631, -58.5140043)",3.451622,1.0,1.000000,"Ingeniería, Otras Ciencias Aplicadas",2018,Inst. Sta. María de los Angeles,Universidad Nacional de San Martín,Instituto de Tecnología Nuclear Dan Beninson
22,S0191,U465,"(-34.5592978754, -58.480213253)","(-34.5729631, -58.5140043)",3.451622,1.0,1.000000,"Ingeniería, Otras Ciencias Aplicadas",2018,Inst. Sta. María de los Angeles,Universidad Nacional de San Martín,Instituto de Tecnología Prof. Jorge Sábato
23,S0191,U465,"(-34.5592978754, -58.480213253)","(-34.5729631, -58.5140043)",3.451622,1.0,1.000000,"Ingeniería, Otras Ciencias Aplicadas",2018,Inst. Sta. Clara de Asís,Universidad Nacional de San Martín,Instituto de Investigaciones Biotecnológicas
24,S0191,U465,"(-34.5592978754, -58.480213253)","(-34.5729631, -58.5140043)",3.451622,1.0,1.000000,"Ingeniería, Otras Ciencias Aplicadas",2018,Inst. Sta. Clara de Asís,Universidad Nacional de San Martín,Instituto de Tecnología Nuclear Dan Beninson
25,S0191,U465,"(-34.5592978754, -58.480213253)","(-34.5729631, -58.5140043)",3.451622,1.0,1.000000,"Ingeniería, Otras Ciencias Aplicadas",2018,Inst. Sta. Clara de Asís,Universidad Nacional de San Martín,Instituto de Tecnología Prof. Jorge Sábato
67,S0268,U088,"(-34.939008, -58.262325)","(-34.7342286, -58.3901502)",25.549943,2.0,1.061705,"Ingeniería, Otras Ciencias Aplicadas",2003,ESCUELA DE EDUCACIÓN SECUNDARIA Nº15,Universidad Nacional de Lanús,Departamento de Desarrollo Productivo y Tecnol...
68,S0268,U088,"(-34.939008, -58.262325)","(-34.7342286, -58.3901502)",25.549943,2.0,1.061705,"Ingeniería, Otras Ciencias Aplicadas",2003,"ESCUELA DE EDUCACION MEDIA Nº12 ""CAMINO A LA L...",Universidad Nacional de Lanús,Departamento de Desarrollo Productivo y Tecnol...
41,S0268,U107,"(-34.939008, -58.262325)","(-34.70629, -58.27705)",25.852235,3.0,1.074267,"Ingeniería, Otras Ciencias Aplicadas",2003,ESCUELA DE EDUCACIÓN SECUNDARIA Nº15,Universidad Nacional de Quilmes,Departamento de Ciencia y Tecnología
42,S0268,U107,"(-34.939008, -58.262325)","(-34.70629, -58.27705)",25.852235,3.0,1.074267,"Ingeniería, Otras Ciencias Aplicadas",2003,"ESCUELA DE EDUCACION MEDIA Nº12 ""CAMINO A LA L...",Universidad Nacional de Quilmes,Departamento de Ciencia y Tecnología
44,S0268,U187,"(-34.939008, -58.262325)","(-34.7963106, -58.2786386)",15.900705,2.0,1.003697,"Ingeniería, Otras Ciencias Aplicadas",2018,ESCUELA DE EDUCACIÓN SECUNDARIA Nº15,Universidad Nacional Arturo Jauretche,Instituto de Ingeniería y Agronomía
45,S0268,U187,"(-34.939008, -58.262325)","(-34.7963106, -58.2786386)",15.900705,2.0,1.003697,"Ingeniería, Otras Ciencias Aplicadas",2018,"ESCUELA DE EDUCACION MEDIA Nº12 ""CAMINO A LA L...",Universidad Nacional Arturo Jauretche,Instituto de Ingeniería y Agronomía
...,...,...,...,...,...,...,...,...,...,...,...,...
46,S2141,U034,"(-34.673237, -58.395901)","(-34.6052849, -58.377483)",7.725030,3.0,1.166531,"Ingeniería, Otras Ciencias Aplicadas",1988,ESCUELA DE EDUCACIÓN SECUNDARIA N° 50,Universidad de la Defensa Nacional,Facultad de la Armada
47,S2141,U034,"(-34.673237, -58.395901)","(-34.6052849, -58.377483)",7.725030,3.0,1.166531,"Ingeniería, Otras Ciencias Aplicadas",1988,ESCUELA DE EDUCACIÓN SECUNDARIA N° 50,Universidad de la Defensa Nacional,Facultad de la Fuerza Aérea
48,S2141,U034,"(-34.673237, -58.395901)","(-34.6052849, -58.377483)",7.725030,5.0,1.166531,"Ingeniería, Otras Ciencias Aplicadas",2003,ESCUELA DE EDUCACIÓN SECUNDARIA N° 50,Universidad de la Defensa Nacional,Facultad de la Armada
49,S2141,U034,"(-34.673237, -58.395901)","(-34.6052849, -58.377483)",7.725030,5.0,1.166531,"Ingeniería, Otras Ciencias Aplicadas",2003,ESCUELA DE EDUCACIÓN SECUNDARIA N° 50,Universidad de la Defensa Nacional,Facultad de la Fuerza Aérea
72,S2141,U080,"(-34.673237, -58.395901)","(-34.6628049, -58.3722248)",2.459352,1.0,1.000000,"Ingeniería, Otras Ciencias Aplicadas",2018,ESCUELA DE EDUCACIÓN SECUNDARIA N° 50,Universidad Nacional de Avellaneda,Departamento de Tecnología y Administración
66,S2141,U088,"(-34.673237, -58.395901)","(-34.7342286, -58.3901502)",6.786595,3.0,1.024821,"Ingeniería, Otras Ciencias Aplicadas",2003,ESCUELA DE EDUCACIÓN SECUNDARIA N° 50,Universidad Nacional de Lanús,Departamento de Desarrollo Productivo y Tecnol...
27,S2141,U206,"(-34.673237, -58.395901)","(-34.7418695, -58.3721061)",7.919678,4.0,1.195924,"Ingeniería, Otras Ciencias Aplicadas",1988,ESCUELA DE EDUCACIÓN SECUNDARIA N° 50,Universidad Nacional de Lomas de Zamora,Facultad de Ingeniería
28,S2141,U206,"(-34.673237, -58.395901)","(-34.7418695, -58.3721061)",7.919678,6.0,1.195924,"Ingeniería, Otras Ciencias Aplicadas",2003,ESCUELA DE EDUCACIÓN SECUNDARIA N° 50,Universidad Nacional de Lomas de Zamora,Facultad de Ingeniería
34,S2141,U353,"(-34.673237, -58.395901)","(-34.694951, -58.327523)",6.713064,2.0,1.013717,"Ingeniería, Otras Ciencias Aplicadas",1988,ESCUELA DE EDUCACIÓN SECUNDARIA N° 50,Universidad Tecnológica Nacional,Facultad Regional Avellaneda
35,S2141,U353,"(-34.673237, -58.395901)","(-34.694951, -58.327523)",6.713064,2.0,1.013717,"Ingeniería, Otras Ciencias Aplicadas",2003,ESCUELA DE EDUCACIÓN SECUNDARIA N° 50,Universidad Tecnológica Nacional,Facultad Regional Avellaneda
69,S2141,U354,"(-34.673237, -58.395901)","(-34.6594074, -58.4691224)",6.884390,4.0,1.039589,"Ingeniería, Otras Ciencias Aplicadas",2003,ESCUELA DE EDUCACIÓN SECUNDARIA N° 50,Universidad Tecnológica Nacional,Facultad Regional Buenos Aires
52,S2141,U380,"(-34.673237, -58.395901)","(-34.6175111, -58.3700019)",6.622225,1.0,1.000000,"Ingeniería, Otras Ciencias Aplicadas",1988,ESCUELA DE EDUCACIÓN SECUNDARIA N° 50,Universidad de Buenos Aires,Facultad de Ingeniería
53,S2141,U380,"(-34.673237, -58.395901)","(-34.6175111, -58.3700019)",6.622225,1.0,1.000000,"Ingeniería, Otras Ciencias Aplicadas",2003,ESCUELA DE EDUCACIÓN SECUNDARIA N° 50,Universidad de Buenos Aires,Facultad de Ingeniería
85,S2610,U153,"(-34.291966, -59.097984)","(-34.1787535, -58.9618508)",17.748470,1.0,1.000000,"Ingeniería, Otras Ciencias Aplicadas",1988,INSTITUTO JOSE MANUEL ESTRADA,Universidad Tecnológica Nacional,Facultad Regional Delta
86,S2610,U153,"(-34.291966, -59.097984)","(-34.1787535, -58.9618508)",17.748470,1.0,1.000000,"Ingeniería, Otras Ciencias Aplicadas",2003,INSTITUTO JOSE MANUEL ESTRADA,Universidad Tecnológica Nacional,Facultad Regional Delta
87,S2610,U153,"(-34.291966, -59.097984)","(-34.1787535, -58.9618508)",17.748470,1.0,1.000000,"Ingeniería, Otras Ciencias Aplicadas",2018,INSTITUTO JOSE MANUEL ESTRADA,Universidad Tecnológica Nacional,Facultad Regional Delta
40,S2951,U107,"(-34.767125, -58.288043)","(-34.70629, -58.27705)",6.823453,1.0,1.000000,"Ingeniería, Otras Ciencias Aplicadas",2003,INSTITUTO SAN JOSE OBRERO,Universidad Nacional de Quilmes,Departamento de Ciencia y Tecnología
43,S2951,U187,"(-34.767125, -58.288043)","(-34.7963106, -58.2786386)",3.350221,1.0,1.000000,"Ingeniería, Otras Ciencias Aplicadas",2018,INSTITUTO SAN JOSE OBRERO,Universidad Nacional Arturo Jauretche,Instituto de Ingeniería y Agronomía
26,S2951,U206,"(-34.767125, -58.288043)","(-34.7418695, -58.3721061)",8.190895,1.0,1.000000,"Ingeniería, Otras Ciencias Aplicadas",1988,INSTITUTO SAN JOSE OBRERO,Universidad Nacional de Lomas de Zamora,Facultad de Ingeniería
33,S2951,U353,"(-34.767125, -58.288043)","(-34.694951, -58.327523)",8.785263,2.0,1.072565,"Ingeniería, Otras Ciencias Aplicadas",1988,INSTITUTO SAN JOSE OBRERO,Universidad Tecnológica Nacional,Facultad Regional Avellaneda
73,S3494,U080,"(-34.6504649012, -58.3892905488)","(-34.6628049, -58.3722248)",2.078763,1.0,1.000000,"Ingeniería, Otras Ciencias Aplicadas",2018,Inst. Sagrado Corazón,Universidad Nacional de Avellaneda,Departamento de Tecnología y Administración
54,S3494,U380,"(-34.6504649012, -58.3892905488)","(-34.6175111, -58.3700019)",4.061052,1.0,1.000000,"Ingeniería, Otras Ciencias Aplicadas",1988,Inst. Sagrado Corazón,Universidad de Buenos Aires,Facultad de Ingeniería
55,S3494,U380,"(-34.6504649012, -58.3892905488)","(-34.6175111, -58.3700019)",4.061052,1.0,1.000000,"Ingeniería, Otras Ciencias Aplicadas",2003,Inst. Sagrado Corazón,Universidad de Buenos Aires,Facultad de Ingeniería
6,S3526,U008,"(-34.6501881126, -58.4786526967)","(-34.5751866667, -58.4367866667)",9.163476,1.0,1.000000,"Ingeniería, Otras Ciencias Aplicadas",1988,Inst. Ntra. Sra. de los Remedios,"Instituto Universitario del Ejército ""Mayor Fr...",Unidad Académica Escuela Superior Técnica
7,S3526,U008,"(-34.6501881126, -58.4786526967)","(-34.5751866667, -58.4367866667)",9.163476,1.0,1.000000,"Ingeniería, Otras Ciencias Aplicadas",1988,Inst. Ntra. Sra. de los Remedios,Universidad de la Defensa Nacional,Facultad del Ejército
50,S3526,U034,"(-34.6501881126, -58.4786526967)","(-34.6052849, -58.377483)",10.529963,2.0,1.149123,"Ingeniería, Otras Ciencias Aplicadas",1988,Inst. Ntra. Sra. de los Remedios,Universidad de la Defensa Nacional,Facultad de la Armada
51,S3526,U034,"(-34.6501881126, -58.4786526967)","(-34.6052849, -58.377483)",10.529963,2.0,1.149123,"Ingeniería, Otras Ciencias Aplicadas",1988,Inst. Ntra. Sra. de los Remedios,Universidad de la Defensa Nacional,Facultad de la Fuerza Aérea
70,S3526,U354,"(-34.6501881126, -58.4786526967)","(-34.6594074, -58.4691224)",1.345078,1.0,1.000000,"Ingeniería, Otras Ciencias Aplicadas",2003,Inst. Ntra. Sra. de los Remedios,Universidad Tecnológica Nacional,Facultad Regional Buenos Aires
71,S3526,U354,"(-34.6501881126, -58.4786526967)","(-34.6594074, -58.4691224)",1.345078,1.0,1.000000,"Ingeniería, Otras Ciencias Aplicadas",2018,Inst. Ntra. Sra. de los Remedios,Universidad Tecnológica Nacional,Facultad Regional Buenos Aires
56,S3526,U380,"(-34.6501881126, -58.4786526967)","(-34.6175111, -58.3700019)",10.601517,3.0,1.156932,"Ingeniería, Otras Ciencias Aplicadas",1988,Inst. Ntra. Sra. de los Remedios,Universidad de Buenos Aires,Facultad de Ingeniería

## Directions

In [19]:
# This gives a helpful hint to what the zona is...
univ_zona_refs = sedes_AMBA_pub_z.groupby('zona_id').first().reset_index()[['zona_id', 'Universidad', 'Facultad']]

NameError: name 'sedes_AMBA_pub_z' is not defined

In [30]:
API_key = 'AIzaSyA-lr2wWmMhakKvPGPUlGje4gZXLrUJ99k'

df = distances.loc[distances.ranking < 3].reset_index()
df

,zona_id_x,lat_x,lng_x,coords_x,key,zona_id_y,lat_y,lng_y,coords_y
0,S000682,-34.907574,-57.963810,"(-34.907574, -57.96381)",0,U000019,-34.574510,-58.436125,"(-34.57451, -58.436125)"
1,S000682,-34.907574,-57.963810,"(-34.907574, -57.96381)",0,U000015,-34.910793,-57.931150,"(-34.9107929, -57.9311498667)"
2,S000682,-34.907574,-57.963810,"(-34.907574, -57.96381)",0,U000001,-34.597670,-58.398865,"(-34.5976701625, -58.3988650875)"
3,S000682,-34.907574,-57.963810,"(-34.907574, -57.96381)",0,U000311,-34.609340,-58.591850,"(-34.60934, -58.59185)"
4,S000682,-34.907574,-57.963810,"(-34.907574, -57.96381)",0,U000052,-34.901127,-57.934941,"(-34.9011268, -57.93494075)"
5,S000683,-34.925977,-57.946744,"(-34.925977, -57.946744)",0,U000019,-34.574510,-58.436125,"(-34.57451, -58.436125)"
6,S000683,-34.925977,-57.946744,"(-34.925977, -57.946744)",0,U000015,-34.910793,-57.931150,"(-34.9107929, -57.9311498667)"
7,S000683,-34.925977,-57.946744,"(-34.925977, -57.946744)",0,U000001,-34.597670,-58.398865,"(-34.5976701625, -58.3988650875)"
8,S000683,-34.925977,-57.946744,"(-34.925977, -57.946744)",0,U000311,-34.609340,-58.591850,"(-34.60934, -58.59185)"
9,S000683,-34.925977,-57.946744,"(-34.925977, -57.946744)",0,U000052,-34.901127,-57.934941,"(-34.9011268, -57.93494075)"
10,S000684,-34.953944,-57.972944,"(-34.953944, -57.972944)",0,U000019,-34.574510,-58.436125,"(-34.57451, -58.436125)"
11,S000684,-34.953944,-57.972944,"(-34.953944, -57.972944)",0,U000015,-34.910793,-57.931150,"(-34.9107929, -57.9311498667)"
12,S000684,-34.953944,-57.972944,"(-34.953944, -57.972944)",0,U000001,-34.597670,-58.398865,"(-34.5976701625, -58.3988650875)"
13,S000684,-34.953944,-57.972944,"(-34.953944, -57.972944)",0,U000311,-34.609340,-58.591850,"(-34.60934, -58.59185)"
14,S000684,-34.953944,-57.972944,"(-34.953944, -57.972944)",0,U000052,-34.901127,-57.934941,"(-34.9011268, -57.93494075)"
15,S000685,-34.869318,-58.048655,"(-34.869318, -58.048655)",0,U000019,-34.574510,-58.436125,"(-34.57451, -58.436125)"
16,S000685,-34.869318,-58.048655,"(-34.869318, -58.048655)",0,U000015,-34.910793,-57.931150,"(-34.9107929, -57.9311498667)"
17,S000685,-34.869318,-58.048655,"(-34.869318, -58.048655)",0,U000001,-34.597670,-58.398865,"(-34.5976701625, -58.3988650875)"
18,S000685,-34.869318,-58.048655,"(-34.869318, -58.048655)",0,U000311,-34.609340,-58.591850,"(-34.60934, -58.59185)"
19,S000685,-34.869318,-58.048655,"(-34.869318, -58.048655)",0,U000052,-34.901127,-57.934941,"(-34.9011268, -57.93494075)"
20,S000208,-34.892841,-57.962711,"(-34.892841, -57.962711)",0,U000019,-34.574510,-58.436125,"(-34.57451, -58.436125)"
21,S000208,-34.892841,-57.962711,"(-34.892841, -57.962711)",0,U000015,-34.910793,-57.931150,"(-34.9107929, -57.9311498667)"
22,S000208,-34.892841,-57.962711,"(-34.892841, -57.962711)",0,U000001,-34.597670,-58.398865,"(-34.5976701625, -58.3988650875)"
23,S000208,-34.892841,-57.962711,"(-34.892841, -57.962711)",0,U000311,-34.609340,-58.591850,"(-34.60934, -58.59185)"
24,S000208,-34.892841,-57.962711,"(-34.892841, -57.962711)",0,U000052,-34.901127,-57.934941,"(-34.9011268, -57.93494075)"
25,S000209,-34.887760,-58.125743,"(-34.88776, -58.125743)",0,U000019,-34.574510,-58.436125,"(-34.57451, -58.436125)"
26,S000209,-34.887760,-58.125743,"(-34.88776, -58.125743)",0,U000015,-34.910793,-57.931150,"(-34.9107929, -57.9311498667)"
27,S000209,-34.887760,-58.125743,"(-34.88776, -58.125743)",0,U000001,-34.597670,-58.398865,"(-34.5976701625, -58.3988650875)"
28,S000209,-34.887760,-58.125743,"(-34.88776, -58.125743)",0,U000311,-34.609340,-58.591850,"(-34.60934, -58.59185)"
29,S000209,-34.887760,-58.125743,"(-34.88776, -58.125743)",0,U000052,-34.901127,-57.934941,"(-34.9011268, -57.93494075)"
...,...,...,...,...,...,...,...,...,...
17085,S003534,-34.642669,-58.520200,"(-34.6426692788, -58.5202001811)",0,U000019,-34.574510,-58.436125,"(-34.57451, -58.436125)"
17086,S003534,-34.642669,-58.520200,"(-34.6426692788, -58.5202001811)",0,U000015,-34.910793,-57.931150,"(-34.9107929, -57.9311498667)"
17087,S003534,-34.642669,-58.520200,"(-34.6426692788, -58.5202001811)",0,U000001,-34.597670,-58.398865,"(-34.5976701625, -58.3988650875)"
17088,S003534,-34.642669,-58.520200,"(-34.6426692788, -58.5202001811)",0,U000311,-34.609340,-58.591850,"(-34.60934, -58.59185)"
17089,S003534,-34.642669,-58.520200,"(-34.6426692788, -58.5202001811)",0,U000052,-34.901127,-57.934941,"(-34.9011268, -57.93494075)"
17090,S003535,-34.662117,-58.506842,"(-34.6621165063, -58.5068416651)",0,U000019,-34.574510,-58.436125,"(-34.57451, -58.436125)"
17091,S003535,-34.662117,-58.506842,"(-34.6621165063, -58.5068416651)",0,U000015,-34.910793,-57.931150,"(-34.9107929, -57.9311498667)"
17092,S003535,-34.662117,-58.506842,"(-34.6621165063, -58.5068416651)",0,U000001,-34.597670,-58.398865,"(-34.5976701625, -58.3988650875)"
17093,S003535,-34.662117,-58.506842,"(-34.6621165063, -58.5068416651)",0,U000311,-34.609340,-58.591850,"(-34.60934, -58.59185)"
17094,S003535,-34.662117,-58.506842,"(-34.6621165063, -58.5068416651)",0,U000052,-34.901127,-57.934941,"(-34.9011268, -57.93494075)"
17095,S003536,-34.668072,-58.507054,"(-34.6680716005, -58.5070539528)",0,U000019,-34.574510,-58.436125,"(-34.57451, -58.436125)"
17096,S003536,-34.668072,-58.507054,"(-34.6680716005, -58.5070539528)",0,U000015,-34.910793,-57.931150,"(-34.9107929, -57.9311498667)"
17097,S003536,-34.668072,-58.507054,"(-34.6680716005, -58.5070539528)",0,U000001,-34.597670,-58.398865,"(-34.5976701625, -58.3988650875)"
17098,S003536,-34.668072,-58.507054,"(-34.6680716005, -58.5070539528)",0,U000311,-34.609340,-58.591850,"(-34.60934, -58.59185)"
17099,S003536,-34.668072,-58.507054,"(-34.6680716005, -58.5070539528)",0,U000052,-34.901127,-57.934941,"(-34.9011268, -57.93494075)"
17100,S003537,-34.669804,-58.502764,"(-34.6698036042, -58.5027635305)",0,U000019,-34.574510,-58.436125,"(-34.57451, -58.436125)"
17101,S003537,-34.669804,-58.502764,"(-34.6698036042, -58.5027635305)",0,U000015,-34.910793,-57.931150,"(-34.9107929, -57.9311498667)"
17102,S003537,-34.669804,-58.502764,"(-34.6698036042, -58.5027635305)",0,U000001,-34.597670,-58.398865,"(-34.5976701625, -58.3988650875)"
17103,S003537,-34.669804,-58.502764,"(-34.6698036042, -58.5027635305)",0,U000311,-34.609340,-58.591850,"(-34.60934, -58.59185)"
17104,S003537,-34.669804,-58.502764,"(-34.6698036042, -58.5027635305)",0,U000052,-34.901127,-57.934941,"(-34.9011268, -57.93494075)"
17105,S003538,-34.654932,-58.526096,"(-34.6549321531, -58.5260955442)",0,U000019,-34.574510,-58.436125,"(-34.57451, -58.436125)"
17106,S003538,-34.654932,-58.526096,"(-34.6549321531, -58.5260955442)",0,U000015,-34.910793,-57.931150,"(-34.9107929, -57.9311498667)"
17107,S003538,-34.654932,-58.526096,"(-34.6549321531, -58.5260955442)",0,U000001,-34.597670,-58.398865,"(-34.5976701625, -58.3988650875)"
17108,S003538,-34.654932,-58.526096,"(-34.6549321531, -58.5260955442)",0,U000311,-34.609340,-58.591850,"(-34.60934, -58.59185)"
17109,S003538,-34.654932,-58.526096,"(-34.6549321531, -58.5260955442)",0,U000052,-34.901127,-57.934941,"(-34.9011268, -57.93494075)"
17110,S003539,-34.634463,-58.521294,"(-34.6344625784, -58.5212938118)",0,U000019,-34.574510,-58.436125,"(-34.57451, -58.436125)"
17111,S003539,-34.634463,-58.521294,"(-34.6344625784, -58.5212938118)",0,U000015,-34.910793,-57.931150,"(-34.9107929, -57.9311498667)"
17112,S003539,-34.634463,-58.521294,"(-34.6344625784, -58.5212938118)",0,U000001,-34.597670,-58.398865,"(-34.5976701625, -58.3988650875)"
17113,S003539,-34.634463,-58.521294,"(-34.6344625784, -58.5212938118)",0,U000311,-34.609340,-58.591850,"(-34.60934, -58.59185)"
17114,S003539,-34.634463,-58.521294,"(-34.6344625784, -58.5212938118)",0,U000052,-34.901127,-57.934941,"(-34.9011268, -57.93494075)"

In [31]:
import urllib, urllib2, json

def coord_format(coord_tup):
    return str(coord_tup[0])+', '+str(coord_tup[1])

def direction_response(row, API_key = None):
    
    base_url = 'https://maps.googleapis.com/maps/api/directions/json?'

    # This joins the parts of the URL together into one string.
    url = base_url + urllib.urlencode({
        'origin': "%s" % (coord_format(row['coords_o'])),
        'destination': "%s" % (coord_format(row['coords_d'])),
        'mode': "%s" % ('transit'),
        'arrival_time': "%s" % ('1540209600'), # plus 604800 s per week
        'key': API_key,
    })
    response = str(urllib2.urlopen(url).read())
    result = [json.loads(response.replace('\\n', ''))]
    return result

In [36]:
import numpy as np

def direction_for_df(df, history_df = None):
    if history_df is None:
        history_df = df[['coords_o', 'coords_d']]
        history_df['direction_response'] = np.nan
              
#     merged = df.merge(history_df, how = 'left')

    for i, row in merged.loc[merged.direction_response.isnull()].iterrows():
        print 'request '+str(i)
        try: 
            
            merged.loc[i, 'direction_response'] = direction_response(row, API_key = 'AIzaSyA-lr2wWmMhakKvPGPUlGje4gZXLrUJ99k')
        except ValueError:
            pass
        
    updated_history = pd.concat([history_df, merged], sort = True)[['coords_d','coords_o','direction_response']].dropna().drop_duplicates(subset = ['coords_d','coords_o'])
    updated_history.to_csv('directions_response_history.csv', index = False)
    
    return merged

In [37]:
import ast
history_df = pd.read_csv('directions_response_history.csv', converters={"coords_o": ast.literal_eval, "coords_d": ast.literal_eval}).drop_duplicates()

df = distances#.loc[distances.ranking < 3].reset_index()

df_with_dirs = direction_for_df(df, history_df)

NameError: global name 'merged' is not defined

### Process responses

In [611]:
df_with_dirs.to_csv('df_with_dirs.csv', index = False)

In [612]:
df_with_dirs = pd.read_csv('./df_with_dirs.csv', converters={"coords_o": ast.literal_eval, "coords_d": ast.literal_eval})

In [614]:

df_with_dirs.columns = pd.MultiIndex.from_product([['match'], df_with_dirs.columns])

for i in range(len(df_with_dirs)):
    try:
        response = ast.literal_eval(df_with_dirs[('match', 'direction_response')][i])
        print routes.keys()
        try: 
            routes = response['routes'][0]
            try: 
                print routes['fare']
            except KeyError:
                print '\n route keys: '+str(routes.keys())+'\n'

            print routes['overview_polyline']
            
#             print routes['legs'][0]['steps'][0].keys()
                
        except IndexError:
            print '\n no routes \n'
            
    except ValueError:
        print ''
        print 'ValueError at '+str(i)
        print ''

[u'fare', u'overview_polyline', u'warnings', u'bounds', u'waypoint_order', u'summary', u'copyrights', u'legs']
{u'currency': u'ARS', u'value': 13, u'text': u'ARS\xa013.00'}
{u'points': u'jjyrEztkcJASp@AvLMpBClGv@vJvA~YzDdGp@nJpAbJfA|Dh@Fa@REjB?ZIVSLUH]L}EDcBFc@LOd@]~IsF|CkBp@W`E@bPBjL@bMD?Nn@_@'}
[u'fare', u'overview_polyline', u'warnings', u'bounds', u'waypoint_order', u'summary', u'copyrights', u'legs']
{u'currency': u'ARS', u'value': 13.75, u'text': u'ARS\xa013.75'}
{u'points': u'jjyrEztkcJASp@AdGGbHIlGv@vJvAfGx@vQ`CdGp@nJpAbJfA|Dh@Fa@REjB?ZIVSLUH]L}EDcBFc@LOd@]nHqErD{Bz@e@d@EjDBn]DfUHTInB?bBF\\wDl@sHp@yHdAkF|AiI~CaPGo@jBiC`FsGtH_K|CuD~@iAdCiBFJGOgCjBu@gBgC}FcBaEbAq@'}
[u'fare', u'overview_polyline', u'warnings', u'bounds', u'waypoint_order', u'summary', u'copyrights', u'legs']
{u'currency': u'ARS', u'value': 13, u'text': u'ARS\xa013.00'}
{u'points': u'j|mrEblldJbFpHxDlFsBfCzBxCNTHRHf@yADCOlC_@jKaAfLcAdI_A|C]vFc@dMqAnGc@dXiCbKeA|Ea@dEc@X?NBTPvB`C~CnD|EnFIIoAfBgCpD'}

ValueError at 3

[u'fare', u'overview_polyline', u'warnings', u'bounds', u'waypoint_order', u'summary', u'copyrights', u'legs']
{u'currency': u'ARS', u'value': 13.75, u'text': u'ARS\xa013.75'}
{u'points': u'feksEts}bJ}@FKHoC}FIa@uB_F_E_JeIsQsCeGyIqPgZ}j@kEmI{CuGeBaEyB{ESWmGaOcDcH}BmFuEcKsVwj@iEqJyDaJQgALe@Jy@LoBZ}@xAeDvLkXtJsTvQia@h@kAPIzA`DhAdCdBjEfElJzBzEpE|J`ElJfMpYtDjIDj@E^ITMVER@RR\\ZFRGdF^pDTdJXtEMvC?lM_@?XA]|@C?[Da@mFP'}
[u'fare', u'overview_polyline', u'warnings', u'bounds', u'waypoint_order', u'summary', u'copyrights', u'legs']
{u'currency': u'ARS', u'value': 25.75, u'text': u'ARS\xa025.75'}
{u'points': u'lcksEdu}bJfA`CMHJGVh@hIpQjBjErAxCZr@?HnGnNhFjL~AzDhLdXdAvBz@bBrB|E|KtVfGdNxElJ~ChHbEvIbBzDdBlDhBhGj@jBh@bAfDfHzFbM~AvDnKpTpCvF`GhMbFlL`DnH`MbYjJ~SxBjF~EtKvA`DpC|GtA|C`I`RbA|BeBt@eBr@EODPC@DREQpEmBd@WVCdC{@zAo@h@Eh@LLBPAPGNMJQDY@KXc@vAcAlBkATWhCsAzCeBDLu@A'}
[u'fare', u'overview_polyline', u'warnings', u'bounds', u'waypoint_order', u'summary', u'copyrights', u'legs']
{u'currency': u'ARS', u'value': 12.5, u'text': u'ARS\xa012.50'}
{u'points': u'lekrEzqxcJz@fEwEdBiMzEeFpBMDBLfA`FNz@T`BODZp@DJUkAkAmHc@yBaBqG}C}JoCeJkMad@{IqZoAyDiBmE}@gDuByGyCuIoCiIo@_B_BoF}AaEwAaEeBwFs@sBeBqEiC_IcGmQkEoMmBaGcBqEoBqFUeAOq@S{AO_AIwAQyEKaDEkAC_CCaCSiDKcBOqGy@wHa@{Fy@qE}@cD[{ACu@Li@`AqFYlBo@iBQo@k@BK?@RJY{GNiF_@oO_CoEq@mMaCwJyByKeCcJeC`Ar@@APDADuAk@h@`Cw@Vu@Tq@^kB~CiBjDaBpCcDvDwP~Rm@z@eHtLaLrRiGpKiJfO_C|DsBhD{CdFwClEqBjCo@`BUz@i@pBcBbI_B|G_CfMoCbHeBlFKEEbDQn@Sl@bBjC'}

ValueError at 7

[u'fare', u'overview_polyline', u'warnings', u'bounds', u'waypoint_order', u'summary', u'copyrights', u'legs']
{u'currency': u'ARS', u'value': 26.75, u'text': u'ARS\xa026.75'}
{u'points': u'`whsEjogbJz@jB~@`Cf@e@GMFL_D~BiClBgCfBpA|CzBjFnEyC|DuCvCtGhB|Dp@nAFLrA~@bArB~@bCJrAHr@fA|CzCnHp@~AlDlItAlDvA~C`AdCtDdJdC~GbAbC`FlLtBlFfBlEtErLFPuA`DsFbMuYfp@yO~]}CxGcDxHgFjLKILJi@hAEX^p@l@pAhAhCbB`E~@`CSNJIrBtEtD|InB~EpFlMzC~GjNd\\rBpEpAdDvBvElAvCbDpH\\hAuDnOMENFe@hBhAhC~@A\\A'}
[u'fare', u'overview_polyline', u'warnings', u'bounds', u'waypoint_order', u'summary', u'copyrights', u'legs']
{u'currency': u'ARS', u'value': 17.75, u'text': u'ARS\xa017.75'}
{u'points': u'`whsEjogbJz@jBlA|CJGIFM[uEbD_H~EqE`DqBnAk@\\{C~BcGfE_Ap@aBaEwAyC_C{FiBcEg@m@sDuIcDuH_GoNaByDsA|@eJpGwDcJmDcIyBrFcA`CcLbZa@fA?JBJX\\FJ?L}AdEKGLFMZqAiALJgFzMm@jB_C`GkCtHCFENy@xBwCrHaIzSeBzEcAfC_CnGqEvL{KfZiJpVqDpJsBhFo@rA_BlCiAxAkHhHoF`FwKhKuGlG{ClC_A|@oAdAyDzCkMhKcMxJgIzGsBlBoAvAgDhEmE`GsD`F}AhBk@f@q@d@mIzFaJjGy@b@kAx@{B`BgItFgHpEgLxH{CvBUN{CvBqCbBqErCaAt@uCrB{BzBqBpCyArCkAtCm@jBoKz\\y@`CgEhLiA|C_A`DiAxDIEMsA~@eCgEaDuDcCaD}Bu@k@i@a@'}
[u'fare', u'overview_polyline', u'warnings', u'bounds', u'waypoint_order', u'summary', u'copyrights', u'legs']
{u'currency': u'ARS', u'value': 18.5, u'text': u'ARS\xa018.50'}
{u'points': u'dbisEjlzcJnMkJiCsFcCyFqBsEmHaQiI_RQ}@wAp@CIDL_Ah@aANaCf@[NeKdGs@AOEQMo@mAmE_KgO_^kF}L}EqLsFgM_BgE}AsDeDeIeEuJO_@`DsBpI{FdI_GxGsEpHiFhImFfIsFaAgCyBkF_BkEgJcVmJiTqJ{TaCeFmAiCsC}Gw@cBwHuQ}]sEmMaBw@Kb@{Fn@eJxA_Q\\aJ`@oGf@oFcEa@@OALs@GHaBhBq@?EE?kGc@_Jw@}RcAg\\kBwRcAkKe@_@AqDCsBG{BOaEYeJu@y\\gB_]_BcWkAAj@|CqBE?AElNt@zAk@vAs@bAu@Fi@l@mHVuDnB?xE?dDC'}
[u'fare', u'overview_polyline', u'warnings', u'bounds', u'waypoint_order', u'summary', u'copyrights', u'legs']
{u'currency': u'ARS', u'value': 26.75, u'text': u'ARS\xa026.75'}
{u'points': u'dbisEjlzcJpa@aZhI{F|DoCdCkBqCkGMk@K@DCPl@pCjGzDlJ|C~HdK|VnGzOvVjn@zOx_@bGhOfItShFrMKHLKXr@NK`Aq@EMDLkAt@GDh@pAhDfIfU|j@dHpQp@|AZj@\\h@h@j@~@~@h@VfBl@`E^pOv@rFbAF~B_@JSLGPQbBMhBQ\\SNuBVuD^wIhA}LvA{BPoAR}Af@wBTyIjAsFx@i@DeEd@oB^Y?WGMKMSeBkEMQYGKBc@Re@`@GVDf@~@nBJd@AZIJODa@HoBPqm@bI{G`AgB\\kFhAmFvAkF|AoDjAuGdCqGtCeIjEkBpAaCtBMZ{KlH{HpFm@n@w@jAa@~@g@|A]bBIx@[rI[pAWZQJe@Fi@Ka@i@Ic@?g@D[L[\\[f@QTUvDTrAdAXr@Ax@Wp@YR_@Jc@C_@SOSMYO{@XwIRiBJg@`@wA\\u@|@qA`AeARETCP@TPLZ?lDTnAV~@l@pA~AoALZNZd@`@d@V\\Ht@DrBu@TCRuBNuApC\\?N@Qh@Fq@xIA^@ZNr@'}
[u'fare', u'overview_polyline', u'warnings', u'bounds', u'waypoint_order', u'summary', u'copyrights', u'legs']
{u'currency': u'ARS', u'value': 13.75, u'text': u'ARS\xa013.75'}
{u'points': u'nanrEnfsdJeBPxCjDu@fAbCtCIJFIbDrDhErF|BpCdAqAfGcInCoD|CyDvBwCjHgJj@s@lB|BrEtF|BtCzHuJ|AjBfDsErHqKdJyMrJqN~BcDbCkDdB_CaCsCyQ}Sa@g@h@u@lEyGvBuCvBkDzB}CxEuGhC{DjF}HdBoClBgCv@oA`CcDHHKKb@k@pAoBlAqBoGoHqGoHw@dA'}
[u'fare', u'overview_polyline', u'warnings', u'bounds', u'waypoint_order', u'summary', u'copyrights', u'legs']

 route keys: [u'overview_polyline', u'warnings', u'bounds', u'waypoint_order', u'summary', u'copyrights', u'legs']

{u'points': u'nanrEnfsdJeFf@QCOBS@wDd@{BNuBRm@F@NEN@PJvAaN|KqEpDn@pHf@`Fu@L'}
[u'overview_polyline', u'warnings', u'bounds', u'waypoint_order', u'summary', u'copyrights', u'legs']

 no routes

[u'overview_polyline', u'warnings', u'bounds', u'waypoint_order', u'summary', u'copyrights', u'legs']

 no routes

[u'overview_polyline', u'warnings', u'bounds', u'waypoint_order', u'summary', u'copyrights', u'legs']
{u'currency': u'ARS', u'value': 14.5, u'text': u'ARS\xa014.50'}
{u'points': u'leusEle{dJl@v@JTCRYt@AP~ApBjHjJlAzAERJCjAvBb@dAnA`EaHnByBf@uBr@{DnAcJdCsI`Cc@LUe@yAnA{Af@oCl@mAJm@LoEjAwHrBwAh@W}@k@b@uBnAgA\\eStFqEdAi@JgADsBw@u@[qKsEoDiBuFeCuK{E}B{@{Bs@gO}GcIoDs@a@kPkHsCoA}B{AgBaAiEiBy@k@sAc@iJcEiIuDaIqD{Aw@oAq@}G{DmAc@_Bi@gBaAoBkA[[eAeAo@g@sA}@gAg@wG~AoLvCoPfEUDy@MmA_@oFuCaAo@iBiA}CaByEsCoFuCcLsGw@m@mBeAuJmFqR}KyC_BYKkCk@eA[_HaBcIkBkG}AwC}@oDiA_IyCiDiA}M_FqF_CuDeAoBUi@?iBo@yBo@i@ImCc@eOcDyNgCyA_@u@i@YW]g@M[Ca@@c@H_@P]JGLIL?v@Lp@`@n@x@dAfCLVZvAHlBIhBCzABl@JdANb@f@NNALGNOHWEqA[cDeBuH{CyN_@yCU[]GKBMLKVHxDIdBOr@S\\m@r@_At@sAz@]N]Fc@FoB?gAO}@WgCeAk@O_@D_@J_@LmAS}Ci@gCs@sMmHuHkE{G_EkCwAiLwGeNgIwI_FiEyBsHiC}FmBmBg@sGsAiDk@qD_AiIgDwEiB_GgCqRsH_KmDqVyIUIw@i@iJiFyAgAaBuAsByB{AuAs@g@y@_@uFkBUMo@e@q@u@[_@gBaB}I{IaIiIcDeDqAwAqBeBgJ}IsAiAa@e@oJyIkDkDOSqDeDq@s@_CkBeR{O{BcBiNgLaA}@cCmCoIaKs@iAo@qAyBqEuB_E}FuLqDiHmFwKyA}Ds@uCPeBEa@I]KOQM[I]i@GS]}Cw@kCsA{B_@YwA}BaCmDrBsCbB_C_BmBc@e@uGnJqPhVkV~]oIkJ_DuDs@y@cAvAeD|EIIJH{DxFgCpD'}
[u'fare', u'overview_polyline', u'warnings', u'bounds', u'waypoint_order', u'summary', u'copyrights', u'legs']
{u'currency': u'ARS', u'value': 42.75, u'text': u'ARS\xa042.75'}
{u'points': u'leusEle{dJl@v@JTCRYt@AP~ApBpBlCJMIJOQuCxDoE~FoE`GiD`FgGhIuApA{Af@P|@@HqFdHw@rAo@vASV_AtDWfBuAfHaAxGOr@qCiAwS_JqCw@aAe@kGiCaAe@KQG[c@OyABa@MgCeAqKsEoDiBuFeCuK{E}B{@{Bs@iIuD_MsFuBeAySgJe@S}B{AgBaAiEiBy@k@sAc@yBaAyPuHqJmE{D{B}EoC}@[sAa@mAm@eDoBaBaBo@g@sA}@gAg@cIlBoXdHcCj@e@BiAUm@UoFuCaAo@i@a@}EiCyEsC}CaB{DwBmI}E}@o@_E{BoIuEyOcJ}CcBq@YkAQkA[uGcB}G{AgEeA}DcA}Bs@kGsBiDoAy@_@qBo@qFoBiG}BaFuBi@UuDeAoBUi@?iBo@yBo@uDo@@OANwAWoLiCsLuB_Dq@eAu@c@k@Qc@AeAH_@LWbBgARYL_@Jq@@w@EeA}@oHiAkH{AoIgDeQiHy_@sMur@uD_Sa@gBg@_BgAuCcEqJaFiL_DsHcQaa@_HkPgDwHeE}J}DyHaDcGkBqDgEsJeL_XkIuRu^{z@eFwL}C_H{@{AoAeBkC{CcEqEeCgDqEaH_EaH}@cBUaAS{@C_@Tk@V_AnB}CrGqJtB_DfVw]HMKOmIyGFKILKIOZLJDMhIxGJJLMnHoKvC_EVQREJKFY?ENMHKFWT}@`@s@`HaKjC{Dx@Np@IbBi@^CxA@vBTVEtE`AtQhDhMtBnLbBj[lDdKbAtKh@zFP`cAbC`t@bBfDLpGLvZv@dJTvFXrAdAXr@Ax@Wp@YR_@Jc@C_@SOSMYO{@XwIv@{@l@QT@PFZVRb@Fb@El@ERQ\\o@\\o@VeDQcAs@]_@M]E]Dm@L]VW\\O\\Cd@JVVJRHn@Bb@At@Q~EG\\G\\Q\\YXSH[B_@GSKQWMa@Ca@B]F]NSNOh@UZWvDTp@h@`@ZR`@Fh@C`@K\\KRYR_@Jc@C_@SOSMYO{@XwIJkAReA`@wA\\u@|@qA`AeARE\\C^RHNB^?xCTnAV~@f@fAt@rAj@j@|@d@xAb@|AYr@WVaAl@_H|Dd@]xEWdCA\\Hx@Pb@d@v@hBr@CLDWiBk@e@w@GQ'}
[u'fare', u'overview_polyline', u'warnings', u'bounds', u'waypoint_order', u'summary', u'copyrights', u'legs']
{u'currency': u'ARS', u'value': 13.75, u'text': u'ARS\xa013.75'}
{u'points': u'nptrEbhcdJfAkAU]O@FGzCbFnAvBzAdCrC|EvCpE~BrDrBrDtDbGzFpJJTuF~FwExFoHfIeF~F|B|C{A~AJTJPs@v@iFvFsF~FkCnCwAdBcD`D|I~NtEpHwEjFg@j@`FvHhFvHb@v@^^JIlE`FlGfHZ`@`B}BrFlGfD~D|BbCVZ{ClEw@`AyFbIiDfFqFvHkGwHyDpFeAtA}C`FqDtEkI|LqI~LgF_Gc@i@eD|EaCjDIKJJi@x@qIdM_DrEw@dA'}
[u'fare', u'overview_polyline', u'warnings', u'bounds', u'waypoint_order', u'summary', u'copyrights', u'legs']
{u'currency': u'ARS', u'value': 37, u'text': u'ARS\xa037.00'}
{u'points': u'nptrEbhcdJfAkAQWHKIJeC_E_HgLwJkPyBsDwBmEy@kBuB_Eu@uAaByD_BsDDGEDcA_CaCoFmB{CcBoCkAaBqDqEaFaFeBmB{BwBiFwEmFkF{@_A_HqHoAyAOU_@yAmB{Jg@uBsEsIuIuOaGmKwAcCJKGFOYsAfBACvSgYlD{E\\Ub@u@z@sArCgEXYWQgDkAoOcFaDkAdBsCdBsCLLE?cA~AKK'}

In [668]:
import shapely.geometry as geometry

# df_with_dirs.columns = pd.MultiIndex.from_product([['match'], df_with_dirs.columns])
formatted_row_list = []

for i in range(len(df_with_dirs)):
    try:
        response = ast.literal_eval(df_with_dirs[('match', 'direction_response')][i])

        row = pd.DataFrame(response['routes'])

        #OK
        a = pd.DataFrame(pd.DataFrame(row['fare'][0], index = ['fare']).T.unstack(), columns=[i]).T
        b = pd.DataFrame(pd.DataFrame(row['overview_polyline'][0], index = [i]))
        b.columns = pd.MultiIndex.from_tuples([['path', 'points']])
        b[('path', 'Line')]  = [geometry.LineString(decode_polyline(b[('path','points')][i]))]

        legs = row['legs'][0][0]
        c = pd.DataFrame(pd.DataFrame(legs['distance'], index = ['distance']).T.unstack(), columns=[i]).T
        d = pd.DataFrame(pd.DataFrame(legs['departure_time'], index = ['departure_time']).T.unstack(), columns=[i]).T
        e = pd.DataFrame(pd.DataFrame(legs['duration'], index = ['duration']).T.unstack(), columns=[i]).T
        f = pd.DataFrame(pd.DataFrame(legs['arrival_time'], index = ['arrival_time']).T.unstack(), columns=[i]).T
        g = pd.DataFrame(pd.DataFrame(legs['end_location'], index = ['end_location']).T.unstack(), columns=[i]).T
        h = pd.DataFrame(pd.DataFrame(legs['start_location'], index = ['start_location']).T.unstack(), columns=[i]).T
        formatted_row = pd.concat([a, b, c, d, e, f, g, h], axis = 1)
        formatted_row_list += [formatted_row]
    
    except:
        pass
result = pd.concat([df_with_dirs, pd.concat(formatted_row_list)], axis = 1)

# print result_list[0]['routes'][0]['legs'][0]['steps'][0].keys()

In [755]:
result

   match                                            \
   index zona_id                          coords_o
0   3720      49          (-34.705258, -58.391971)
1   3720      39          (-34.705258, -58.391971)
2   2459      63           (-34.64657, -58.559594)
3   2459     393           (-34.64657, -58.559594)
4   3696      86          (-34.796518, -58.320114)
5   3696     100          (-34.796518, -58.320114)
6    359      67  (-34.6328257032, -58.4580071808)
7    359     377  (-34.6328257032, -58.4580071808)
8   1742      86           (-34.78419, -58.206641)
9   1742      72           (-34.78419, -58.206641)
10  4495      49          (-34.785707, -58.467253)
11  4495      74          (-34.785707, -58.467253)
12   707      63          (-34.647419, -58.594264)
13   707     393          (-34.647419, -58.594264)
14  4233      68          (-34.957575, -57.818005)
15  4233     412          (-34.957575, -57.818005)
16  3235      63          (-34.847699, -58.635328)
17  3235      74          (-34.847699, -58.635328)
18  2653      63            (-34.6805, -58.512726)
19  2653     377            (-34.6805, -58.512726)

                                                          \
                            coords_d distance_km ranking
0         (-34.7342286, -58.3901502)    3.218191     1.0
1         (-34.7418695, -58.3721061)    4.450452     2.0
2         (-34.6705129, -58.5650592)    2.702922     1.0
3         (-34.6404207, -58.6014921)    3.901417     2.0
4         (-34.7963106, -58.2786386)    3.795637     1.0
5         (-34.8367059, -58.3832381)    7.295954     2.0
6   (-34.5751866667, -58.4367866667)    6.683797     2.0
7         (-34.6594074, -58.4691224)    3.119929     1.0
8         (-34.7963106, -58.2786386)    6.725050     1.0
9             (-34.70629, -58.27705)   10.781980     2.0
10        (-34.7342286, -58.3901502)    9.079859     2.0
11        (-34.7892088, -58.5254058)    5.336512     1.0
12        (-34.6705129, -58.5650592)    3.705408     2.0
13        (-34.6404207, -58.6014921)    1.020721     1.0
14        (-34.8995323, -57.9385431)   12.757559     2.0
15        (-34.9047511, -57.9281661)   11.646590     1.0
16        (-34.6705129, -58.5650592)   20.682389     2.0
17        (-34.7892088, -58.5254058)   11.968339     1.0
18        (-34.6705129, -58.5650592)    4.922486     2.0
19        (-34.6594074, -58.4691224)    4.631027     1.0

                                                          fare             \
                                   direction_response currency       text
0   {u'routes': [{u'fare': {u'currency': u'ARS', u...      ARS  ARS 13.00
1   {u'routes': [{u'fare': {u'currency': u'ARS', u...      ARS  ARS 13.75
2   {u'routes': [{u'fare': {u'currency': u'ARS', u...      ARS  ARS 13.00
3                                                 NaN      NaN        NaN
4   {u'routes': [{u'fare': {u'currency': u'ARS', u...      ARS  ARS 13.75
5   {u'routes': [{u'fare': {u'currency': u'ARS', u...      ARS  ARS 25.75
6   {u'routes': [{u'fare': {u'currency': u'ARS', u...      ARS  ARS 12.50
7                                                 NaN      NaN        NaN
8   {u'routes': [{u'fare': {u'currency': u'ARS', u...      ARS  ARS 26.75
9   {u'routes': [{u'fare': {u'currency': u'ARS', u...      ARS  ARS 17.75
10  {u'routes': [{u'fare': {u'currency': u'ARS', u...      ARS  ARS 18.50
11  {u'routes': [{u'fare': {u'currency': u'ARS', u...      ARS  ARS 26.75
12  {u'routes': [{u'fare': {u'currency': u'ARS', u...      ARS  ARS 13.75
13  {u'routes': [{u'overview_polyline': {u'points'...      NaN        NaN
14  {u'routes': [], u'status': u'ZERO_RESULTS', u'...      NaN        NaN
15  {u'routes': [], u'status': u'ZERO_RESULTS', u'...      NaN        NaN
16  {u'routes': [{u'fare': {u'currency': u'ARS', u...      ARS  ARS 14.50
17  {u'routes': [{u'fare': {u'currency': u'ARS', u...      ARS  ARS 42.75
18  {u'routes': [{u'fare': {u'currency': u'ARS', u...      ARS  ARS 13.75
19  {u'routes': [{u'fare': {u'currency': u'ARS', u...      ARS  ARS 37.00

                                                        path  \
    value                                             points
0      13  jjyrEztkcJASp@AvLMpBClGv@vJvA~YzDdGp@nJpAbJfA|...
1   13.75  jjyrEztkcJASp@AdGGbHIlGv@vJvAfGx@vQ`CdGp@nJpAb...
2      13  j|mrEblldJbFpHxDlFsBfCzBxCNTHRHf@yADCOlC_@jKaA...
3     NaN                                                NaN
4   13.75  feksEts}bJ}@FKHoC}FIa@uB_F_E_JeIsQsCeGyIqPgZ}j...
5   25.75  lcksEdu}bJfA`CMHJGVh@hIpQjBjErAxCZr@?HnGnNhFjL...
6    12.5  lekrEzqxcJz@fEwEdBiMzEeFpBMDBLfA`FNz@T`BODZp@D...
7     NaN                                                NaN
8   26.75  `whsEjogbJz@jB~@`Cf@e@GMFL_D~BiClBgCfBpA|CzBjF...
9   17.75  `whsEjogbJz@jBlA|CJGIFM[uEbD_H~EqE`DqBnAk@\{C~...
10   18.5  dbisEjlzcJnMkJiCsFcCyFqBsEmHaQiI_RQ}@wAp@CIDL_...
11  26.75  dbisEjlzcJpa@aZhI{F|DoCdCkBqCkGMk@K@DCPl@pCjGz...
12  13.75  nanrEnfsdJeBPxCjDu@fAbCtCIJFIbDrDhErF|BpCdAqAf...
13    NaN                                                NaN
14    NaN                                                NaN
15    NaN                                                NaN
16   14.5  leusEle{dJl@v@JTCRYt@AP~ApBjHjJlAzAERJCjAvBb@d...
17  42.75  leusEle{dJl@v@JTCRYt@AP~ApBpBlCJMIJOQuCxDoE~Fo...
18  13.75  nptrEbhcdJfAkAU]O@FGzCbFnAvBzAdCrC|EvCpE~BrDrB...
19     37  nptrEbhcdJfAkAQWHKIJeC_E_HgLwJkPyBsDwBmEy@kBuB...

                                                      distance         \
                                                 Line     text  value
0   LINESTRING (-34.70518 -58.39198, -34.70517 -58...   3.5 km   3504
1   LINESTRING (-34.70518 -58.39198, -34.70517 -58...   5.9 km   5888
2   LINESTRING (-34.64662 -58.55954, -34.64776 -58...   3.4 km   3439
3                                                 NaN      NaN    NaN
4   LINESTRING (-34.79652 -58.32011, -34.79621 -58...   9.2 km   9243
5   LINESTRING (-34.79623 -58.32035, -34.79659 -58...   8.2 km   8159
6   LINESTRING (-34.63271 -58.45806, -34.63301 -58...  12.4 km  12436
7                                                 NaN      NaN    NaN
8   LINESTRING (-34.78401 -58.20678, -34.78431 -58...   8.4 km   8438
9   LINESTRING (-34.78401 -58.20678, -34.78431 -58...  13.5 km  13510
10  LINESTRING (-34.78579 -58.46742, -34.78811 -58...  14.4 km  14389
11  LINESTRING (-34.78579 -58.46742, -34.79132 -58...  14.3 km  14309
12  LINESTRING (-34.64744 -58.59448, -34.64693 -58...   6.0 km   6035
13                                                NaN      NaN    NaN
14                                                NaN      NaN    NaN
15                                                NaN      NaN    NaN
16  LINESTRING (-34.84775 -58.63527, -34.84798 -58...  26.1 km  26065
17  LINESTRING (-34.84775 -58.63527, -34.84798 -58...  31.8 km  31805
18  LINESTRING (-34.68056 -58.51282, -34.68092 -58...   7.7 km   7741
19  LINESTRING (-34.68056 -58.51282, -34.68092 -58...   5.9 km   5870

   departure_time                                           duration         \
             text             time_zone       value             text  value
0          8:42am  America/Buenos_Aires  1540208562          16 mins    984
1          8:28am  America/Buenos_Aires  1540207724          31 mins   1836
2          8:27am  America/Buenos_Aires  1540207676          32 mins   1924
3             NaN                   NaN         NaN              NaN    NaN
4          7:54am  America/Buenos_Aires  1540205694          45 mins   2670
5          8:05am  America/Buenos_Aires  1540206352          53 mins   3195
6          8:07am  America/Buenos_Aires  1540206455          50 mins   3020
7             NaN                   NaN         NaN              NaN    NaN
8          7:48am  America/Buenos_Aires  1540205321          51 mins   3082
9          8:08am  America/Buenos_Aires  1540206539          49 mins   2958
10         7:25am  America/Buenos_Aires  1540203931   1 hour 16 mins   4560
11         6:23am  America/Buenos_Aires  1540200226   1 hour 41 mins   6053
12         8:17am  America/Buenos_Aires  1540207023          43 mins   2577
13            NaN                   NaN         NaN              NaN    NaN
14            NaN                   NaN         NaN              NaN    NaN
15            NaN                   NaN         NaN              NaN    NaN
16         6:54am  America/Buenos_Aires  1540202049   2 hours 5 mins   7495
17         5:34am  America/Buenos_Aires  1540197240  3 hours 26 mins  12360
18         8:10am  America/Buenos_Aires  1540206645          41 mins   2440
19         8:14am  America/Buenos_Aires  1540206858          44 mins   2650

   arrival_time                                   end_location             \
           text             time_zone       value          lat        lng
0        8:59am  America/Buenos_Aires  1540209546   -34.734229 -58.390150
1        8:59am  America/Buenos_Aires  1540209560   -34.741876 -58.372120
2        9:00am  America/Buenos_Aires  1540209600   -34.670306 -58.564812
3           NaN                   NaN         NaN          NaN        NaN
4        8:39am  America/Buenos_Aires  1540208364   -34.796313 -58.278686
5        8:59am  America/Buenos_Aires  1540209547   -34.836706 -58.383238
6        8:57am  America/Buenos_Aires  1540209475   -34.575588 -58.436321
7           NaN                   NaN         NaN          NaN        NaN
8        8:40am  America/Buenos_Aires  1540208403   -34.796313 -58.278686
9        8:58am  America/Buenos_Aires  1540209497   -34.706241 -58.277140
10       8:41am  America/Buenos_Aires  1540208491   -34.734228 -58.390182
11       8:04am  America/Buenos_Aires  1540206279   -34.789207 -58.525407
12       9:00am  America/Buenos_Aires  1540209600   -34.670306 -58.564812
13          NaN                   NaN         NaN          NaN        NaN
14          NaN                   NaN         NaN          NaN        NaN
15          NaN                   NaN         NaN          NaN        NaN
16       8:59am  America/Buenos_Aires  1540209544   -34.670306 -58.564812
17       9:00am  America/Buenos_Aires  1540209600   -34.789207 -58.525407
18       8:51am  America/Buenos_Aires  1540209085   -34.670306 -58.564812
19       8:58am  America/Buenos_Aires  1540209508   -34.659403 -58.469111

   start_location
              lat        lng
0      -34.705177 -58.391976
1      -34.705177 -58.391976
2      -34.646619 -58.559539
3             NaN        NaN
4      -34.796518 -58.320114
5      -34.796230 -58.320351
6      -34.632707 -58.458060
7             NaN        NaN
8      -34.784007 -58.206778
9      -34.784007 -58.206778
10     -34.785792 -58.467415
11     -34.785792 -58.467415
12     -34.647445 -58.594482
13            NaN        NaN
14            NaN        NaN
15            NaN        NaN
16     -34.847747 -58.635268
17     -34.847747 -58.635268
18     -34.680563 -58.512816
19     -34.680563 -58.512816

In [675]:
#start
start_info = result[[('match', 'index'), ('departure_time', 'text'), ('start_location', 'lat'), ('start_location', 'lng')]]

#path
paths_info = result[[('fare', 'text'), ('path', 'Line'), ('distance', 'text'), ('duration', 'text')]]

#end
end_info = result[[('match', 'zona_id'), ('match', 'ranking'), ('end_location', 'lat'), ('end_location', 'lng')]]

# geojson.LineString(paths_info[('path', 'Line')][0])
coordinates = []
for line in paths_info[('path', 'Line')]:
    try:
        coordinates += [[[line.xy[0][i], line.xy[1][i]] for i in range(len(line.xy[0]))]]
    except AttributeError:
        coordinates += [np.nan]

In [739]:
# start_info.merge(escuelas_AMBA[['index', 'Matricula est 5to', 'nombre_estab']], left_on = ('match', 'index'), right_on = ('index',))

In [753]:
import geojson

def starts2geojson(df):
    features = []
    insert_features = lambda X: features.append(
            geojson.Feature(geometry=geojson.Point((X[('start_location', 'lng')],
                                                    X[('start_location', 'lat')])),
                            properties=dict(school=X[('match', 'index')],
                                            departure_time=X[('departure_time', 'text')])))
    df.apply(insert_features, axis=1)
    with open('start_info.geojson', 'w') as fp:
        geojson.dump(geojson.FeatureCollection(features), fp, sort_keys=True, ensure_ascii=False)

def ends2geojson(df):
    features = []
    insert_features = lambda X: features.append(
            geojson.Feature(geometry=geojson.Point((X[('end_location', 'lng')],
                                                    X[('end_location', 'lat')])),
                            properties=dict(zona=X[('match', 'zona_id')])))
    df.apply(insert_features, axis=1)
    
    with open('end_info.geojson', 'w') as fp:
        geojson.dump(geojson.FeatureCollection(features), fp, sort_keys=True, ensure_ascii=False)

        
starts2geojson(start_info.dropna())
ends2geojson(end_info.dropna())

## Send to Mapbox

In [754]:
from mapbox import Uploader
import json

username = 'matuteiglesias'
token = 'sk.eyJ1IjoibWF0dXRlaWdsZXNpYXMiLCJhIjoiY2puODA4bW8xMGV1dzNrcGtiOGp6NXQ5aCJ9.DohKmjn_o6MK1Y4Q5FG8ew'

# data = json.load(open('./start_info.geojson'))
# with open('./test/upload_data.geojson', 'w') as outfile:
#     json.dump(data, outfile)/

service = Uploader(access_token=token)
with open('start_info.geojson', 'r') as src:
    upload_resp = service.upload(src, username+'.start_info')
    
with open('end_info.geojson', 'r') as src:
    upload_resp = service.upload(src, username+'.end_info')

In [ ]:
pd.read_csv('st')

In [140]:
def decode_polyline(polyline_str):
    index, lat, lng = 0, 0, 0
    coordinates = []
    changes = {'latitude': 0, 'longitude': 0}

    # Coordinates have variable length when encoded, so just keep
    # track of whether we've hit the end of the string. In each
    # while loop iteration, a single coordinate is decoded.
    while index < len(polyline_str):
        # Gather lat/lon changes, store them in a dictionary to apply them later
        for unit in ['latitude', 'longitude']: 
            shift, result = 0, 0

            while True:
                byte = ord(polyline_str[index]) - 63
                index+=1
                result |= (byte & 0x1f) << shift
                shift += 5
                if not byte >= 0x20:
                    break

            if (result & 1):
                changes[unit] = ~(result >> 1)
            else:
                changes[unit] = (result >> 1)

        lat += changes['latitude']
        lng += changes['longitude']

        coordinates.append((lat / 100000.0, lng / 100000.0))

    return coordinates

In [76]:
row

index                                3720
zona_id                                 5
coords_o         (-34.705258, -58.391971)
coords_d       (-34.7342286, -58.3901502)
distance_km                       3.21819
ranking                                 1
Name: 0, dtype: object